### ISSUE TITLE
Split `_forms.scss` file out into multiple separate files?

### ISSUE THREAD

**Issue by sean-dunwoody** [studio24/amplify#11]
The `assets-src/styles/sass/30-base/_forms.scss` file is one of the largest SCSS files in the project. 

The difference between the `core.css` file size with and without `_forms.scss` included is about 10kb (70.56 kb with _forms.scss, and 60.53 kb without _forms.scss).

Even though 10kb isn't particularly significant in the context of an entire webpage, it represents more than 10% of the default `core.css` file size, and the browser needs to parse it all even if none of it is used.

Alongside this, it can be frustrating if you want to only use a very small number of form styles on a website. Say for example you have a search form, which consists of a label, a text/search input, and a submit button. With the current setup, including the `_forms.scss` file will mean that you're including a significant amount of new CSS to the built files, when you're only going to be using a very small percentage of that new built code.

Some ideas on how we could break it out:

1. Perhaps we could add a new `35-forms` directory in the `assets-src/styles/sass` directory? And then split out the different parts of the form styles in there? E.g. `35-forms/forms-base.scss`, `35-forms/textarea.scss`, `35-forms/radio-and-select.scss`, `35-forms/segmented-options.scss` etc. We could then include only the styles for form elements that we're using (perhaps with all of them included by default for ease of development?)
2. Perhaps we could split the `_forms.scss` file out into two separate files? A simple file (to include some basic form styles), and a more advanced one (to include styles for segmented options, custom checkbox styles etc)?

It might be a bit difficult to break the form styles out, as some of them look dependent on others, but I think it would be worthwhile doing if at all possible. It might also make the form styles easier to manage and add to going forward.

**Comment by NicolaSaunders** [comment]
Thanks for the reminder about this @sean-dunwoody - I agree this would be a good improvement. I'll add a task to the Jira board.

**Comment by NicolaSaunders** [comment]
A pull request has been issued for this: https://github.com/studio24/amplify/pull/16
