### ISSUE TITLE
Implement a table sorting component for Amplify

### ISSUE THREAD

**Issue by sean-dunwoody** [studio24/amplify#27]
In some projects, we've had to implement tables with sortable rows, e.g.

[https://www.hs2.org.uk/supply-chain/direct-contract-opportunities/](https://www.hs2.org.uk/supply-chain/direct-contract-opportunities/)

So you can select a column header, and it will sort all rows in the table either ascending or descending based on the selected column.

For example, if the column is a string, it will sort A-Z, or Z-A. And for numbers, it would sort by the integer value ascending or descending.

At the moment, we tend to implement this via PHP. The problem with this approach is that it is not accessible, and has been flagged up in recent accessibility reports for a couple of sites.

The recommended way to implement this is using JavaScript to [progressively enhance](https://developer.mozilla.org/en-US/docs/Glossary/Progressive_Enhancement) the table, and add sorting functionality in.

To tackle this, we should create a new advanced component within Amplify that adds table sorting to an existing HTML table.

There is already a table component in Amplify that we can use as a basis for this work:

[https://amplify.studio24.net/amplify/fundamentals/tables.html](https://amplify.studio24.net/amplify/fundamentals/tables.html)

I would recommend structuring the files like this:

1. Use the existing table markup as a starting point, but include a new data attribute on the container element (e.g. something like `data-component="sortable-table"` so that we can hook into it with JavaScript
2. Creating an associated SCSS file for the sortable table in the [advanced components directory](https://github.com/studio24/amplify/tree/main/assets-src/styles/sass/60-advanced-components) for any styling that the sortable table would need (and don't forget to load it in the [advanced.scss file](https://github.com/studio24/amplify/blob/main/assets-src/styles/advanced.scss))
3. Setup a `sortable-tables.js` file in the [amplify/assets-src/js/main/](https://github.com/studio24/amplify/tree/main/assets-src/js/main) JavaScript directory, loading it in the [main.js file](https://github.com/studio24/amplify/blob/main/assets-src/js/main.js)

I would approach the JavaScript for this by implementing basic functionality first, and then working on more complex things later, e.g.

1. Get the table headers converted into buttons with the associated aria tags etc.
2. After that, work on actually sorting the data that is in the table depending on user interaction
3. Clean up the styles and final test for accessibility and performance

Separately we will need to look at loading data in for the table via Ajax (e.g. if the table has multiple pages of data), but please don't worry about that for this issue! It would be a big job just on its own, and I think it is best if we tackle this as a separate issue later.

The JavaScript for this component will likely be quite complicated. I would expect it to take a few days to get this completely right.

For information and guides on how to approach this work, please see the following resources:

1. This is a really good guide by Adrian Roselli on how to markup a sortable table (although it doesn't deal with actually sorting the data itself): [https://adrianroselli.com/2021/04/sortable-table-columns.html](https://adrianroselli.com/2021/04/sortable-table-columns.html)
2. The W3C provide a pattern in their WAI ARIA site which is well worth investigating: [https://www.w3.org/WAI/ARIA/apg/patterns/table/examples/sortable-table/](https://www.w3.org/WAI/ARIA/apg/patterns/table/examples/sortable-table/)
3. Array.sort can probably be used to sort the data, but there might be a library that we can use to account for the potential different types of data (e.g. integers, floats, strings, monetary amounts, etc.): [https://gomakethings.com/sorting-an-array-by-multiple-criteria-with-vanilla-javascript/](https://gomakethings.com/sorting-an-array-by-multiple-criteria-with-vanilla-javascript/) and [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort). This one will require some investigation

**Comment by sean-dunwoody** [comment]
@ostafinskim as per our chat yesterday, I've assigned this issue to you. Please add any questions or problems etc. in here, and we can chat them through here or on a call :)

**Comment by ostafinskim** [comment]
Initial PR is ready -> https://github.com/studio24/amplify/pull/28

@todo: 
- disallow column to be sortable
- ARIA improvements
- work on custom types of data in table ( e.g dates )

**Comment by ostafinskim** [comment]
Hiya quick Q about table headings, more precisely should we disallow wrapping ?

On this screenshot there is wrapping going on `th` element:
<img width="1510" alt="text_wrap" src="https://user-images.githubusercontent.com/58887137/219428092-dd00d058-55b9-40f5-9e4a-6eb506fb6347.png">


On this text inside `th` has white-space: nowrap;
<img width="1510" alt="nowrap" src="https://user-images.githubusercontent.com/58887137/219428462-556fc908-34d0-41af-8abb-9a480ae2013b.png">

It plays nicely with responsive tables when nowrap turn on 👍🏻 

Any suggestions, ideas welcomed

**Comment by NicolaSaunders** [comment]
I am now closing this issue as it has been addressed with the release of [version 1.3.0](https://github.com/studio24/amplify/releases/tag/v1.3.0), which has introduced a [pattern for sortable tables](https://amplify.studio24.net/amplify/advanced-components/sortable-tables.html)
