### ISSUE TITLE
Expand Get Started instructions

### ISSUE THREAD

**Issue by simonrjones** [studio24/amplify#6]
Would be great to expand instructions in the Getting Started page so any dev could follow these to include Amplify in their project.

I'd recommend telling people to download files rather than git clone Amplify (since then they'd need to switch the git repo which may get confusing). For reference, this link downloads the current code in main branch: https://github.com/studio24/amplify/archive/refs/heads/main.zip

Add some details on the files / folders you need to copy to your project to start using Amplify. 

And any other useful getting started notes :)

**Comment by NicolaSaunders** [comment]
A pull request has been issued for this: https://github.com/studio24/amplify/pull/9
