### ISSUE TITLE
Document how to release changes to Amplify

### ISSUE THREAD

**Issue by simonrjones** [studio24/amplify#7]
In our dev team meeting it was noted it would be useful to be able to copy in future features / changes in Amplify to existing documents. To help this we could version releases to Amplify and document these in GitHub.

We should add some docs on how to do this to help the team add future releases to Amplify.

**Comment by simonrjones** [comment]
I found an automated way to do this via [GitHub actions](https://github.com/googleapis/release-please). 

This does the following:
- Uses [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) to auto increment version number
- On merging changes into main (e.g. commit directly or via a PR) this auto-creates a Release PR
- Once merged the Release PR then creates a new GitHub Release with the correct version number, updates version.txt with current version & adds an entry to CHANGELOG.md

The only weird thing is you have to remember a second PR is created when merging changes into main which is the Release PR, which has to be merged to create the release. I think the benefit of this is you can do multiple merges into main branch, the release branch is automatically kept up to date with new additions, and then you decide when to create the release. Which I think makes more sense. 

You can ee demo at https://github.com/simonrjones/test-auto-version

/cc @maries24 @sean-dunwoody

**Comment by maries24** [comment]
Hi @simonrjones @sean-dunwoody (/cc @NicolaSaunders)

Would it be possible to clarify the use case for tagging please? I think it's a good thing in general but I'm not sure exactly what the requirement is for Amplify.

Thank you.

**Comment by simonrjones** [comment]
From the training we've done so far it seems people download Amplify and customise it. At which point it becomes different to the original Amplify codebase. However, it is likely there may be features / fixes we do need to update older projects for in the future. 

If someone wants to update their local Apollo code with some new changes how do they do this? If we had some form of versioning it would be easier to see what's changed since you downloaded it. There may be other ways to do this and I know you want to keep things simple with Amplify.

**Comment by maries24** [comment]
Thanks @simonrjones Ok I understand now.
I also think it's good to be able to go back to documentation and code as it was at the time when a specific project was set up.

**Comment by NicolaSaunders** [comment]
I am marking this issue as having been closed by https://github.com/studio24/amplify/pull/24
